name: Dev to main

on:
  pull_request:
    branches: [dev]
    # types: [closed]

jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Set Git config
      run: |
          git config --local user.emails "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Merge dev to main
      run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff dev -m "Auto-merge dev to main"
          git push