on:
  push:
    branches:
    - feature
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      token: ${{ secrets.SECRET_TOKEN }}
      with:
        destination_branch: "main"
